// In Docker, the Next.js server proxies this relative path to Spring Boot.
// Keeping the browser on one origin also avoids CORS and Cookie restrictions.
const API=process.env.NEXT_PUBLIC_API_BASE_URL??"/api/v1";
export type Category="STUDY"|"APP_DEVELOPMENT"|"READING"|"EXERCISE"|"STRENGTH_TRAINING"|"SLEEP"|"OTHER";
export type Activity={id:string;category:Category;durationMinutes:number;expAwarded:number;performedOn:string;createdAt:string};
export type Unlock={key:string;displayName:string;requiredLevel:number};
export type Dashboard={progress:{totalExp:number;level:number;currentLevelExp:number;nextLevelExp:number|null;expToNextLevel:number|null};activeDays:number;todayActivities:Activity[];world:Unlock[]};
async function csrf(){const response=await fetch(`${API}/auth/csrf`,{credentials:"include"});if(!response.ok)throw new Error(`CSRFトークンの取得に失敗しました（${response.status}）`);} function token(){return document.cookie.split("; ").find(x=>x.startsWith("GW-XSRF-TOKEN="))?.split("=")[1]??"";}
async function request<T>(path:string,init:RequestInit={}):Promise<T>{const changing=!!init.method&&init.method!=="GET";if(changing)await csrf();const r=await fetch(`${API}${path}`,{...init,credentials:"include",headers:{"Content-Type":"application/json",...(changing?{"X-XSRF-TOKEN":decodeURIComponent(token())}:{}),...init.headers}});if(!r.ok){const body=await r.text();let detail:string|undefined;try{detail=JSON.parse(body).detail;}catch{}throw new Error(detail??`通信に失敗しました（${r.status}）`);}return r.status===204?undefined as T:await r.json() as T;}
export const api={register:(body:{displayName:string;email:string;password:string})=>request("/auth/register",{method:"POST",body:JSON.stringify(body)}),login:(body:{email:string;password:string})=>request("/auth/login",{method:"POST",body:JSON.stringify(body)}),logout:()=>request("/auth/logout",{method:"POST"}),dashboard:()=>request<Dashboard>("/dashboard"),createActivity:(body:{category:Category;durationMinutes:number})=>request<{activity:Activity;dashboard:Dashboard;newlyUnlocked:Unlock[]}>("/activities",{method:"POST",body:JSON.stringify(body)}),history:(page=0)=>request<{content:Activity[];page:number;totalPages:number}>(`/activities?page=${page}`)};
