"use client";
import Link from "next/link"; import {useEffect,useState} from "react"; import {api,type Dashboard,type Unlock} from "../../lib/api"; import {WorldScene} from "../../components/WorldScene"; import {ActivityForm} from "../../components/ActivityForm"; import {useRouter} from "next/navigation";
const names:Record<string,string>={STUDY:"勉強",APP_DEVELOPMENT:"アプリ開発",READING:"読書",EXERCISE:"運動",STRENGTH_TRAINING:"筋トレ",SLEEP:"睡眠",OTHER:"その他"};
export default function DashboardPage(){
 const router=useRouter(),[data,setData]=useState<Dashboard>(),[celebration,setCelebration]=useState<Unlock[]>([]);
 useEffect(()=>{api.dashboard().then(setData).catch(()=>router.replace("/login"));},[router]);
 if(!data)return <main className="loading">世界を読み込んでいます…</main>;
 const p=data.progress; const ratio=p.nextLevelExp?Math.min(100,((p.totalExp-p.currentLevelExp)/(p.nextLevelExp-p.currentLevelExp))*100):100;
 return <main className="dashboard"><header><Link href="/dashboard" className="brand">✦ GROW WORLD</Link><span><Link href="/history">履歴</Link><button className="link-button" onClick={async()=>{await api.logout();router.push("/");}}>ログアウト</button></span></header><section className="dash-grid"><div className="world-wrap"><WorldScene world={data.world} celebration={celebration}/><div className="world-label">Lv.{p.level} の世界 <span>{data.world.at(-1)?.displayName}</span></div></div><aside><div className="progress-card"><p className="eyebrow">CURRENT PROGRESS</p><div className="level-line"><b>Lv. {p.level}</b><span>{p.totalExp} EXP</span></div>{p.nextLevelExp?<><div className="bar"><i style={{width:`${ratio}%`}}/></div><p>次のレベルまで <strong>{p.expToNextLevel} EXP</strong></p></>:<p>最高レベルに到達しました！</p>}</div><ActivityForm onSubmit={async value=>{const result=await api.createActivity(value);setData(result.dashboard);setCelebration(result.newlyUnlocked);window.setTimeout(()=>setCelebration([]),4500);}}/><div className="today"><div><p className="eyebrow">YOUR RHYTHM</p><b>{data.activeDays}<small> 日 行動した</small></b></div><div><p className="eyebrow">TODAY</p><b>{data.todayActivities.reduce((n,a)=>n+a.durationMinutes,0)}<small> 分</small></b></div></div></aside></section><section className="today-list"><h2>今日の足あと</h2>{data.todayActivities.length===0?<p>最初の行動を記録して、世界に変化を起こそう。</p>:data.todayActivities.map(a=><div key={a.id}><span>{names[a.category]}</span><span>{a.durationMinutes}分 <b>+{a.expAwarded} EXP</b></span></div>)}</section></main>;
}
